version: 2
updates:
  # Enable version updates for npm (Node.js dependencies)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "taskmanagement/core-team"
    assignees:
      - "taskmanagement/devops-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # API package dependencies
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "taskmanagement/backend-team"
    labels:
      - "dependencies"
      - "api"
      - "automated"

  # Web app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "taskmanagement/frontend-team"
    labels:
      - "dependencies"
      - "web"
      - "automated"

  # Admin app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/admin"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "taskmanagement/frontend-team"
    labels:
      - "dependencies"
      - "admin"
      - "automated"

  # Mobile app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "taskmanagement/mobile-team"
    labels:
      - "dependencies"
      - "mobile"
      - "automated"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "taskmanagement/devops-team"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # Docker dependencies for API
  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "taskmanagement/devops-team"
      - "taskmanagement/backend-team"
    labels:
      - "dependencies"
      - "docker"
      - "api"
      - "automated"

  # Docker dependencies for Web
  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "11:00"
    open-pull-requests-limit: 3
    reviewers:
      - "taskmanagement/devops-team"
      - "taskmanagement/frontend-team"
    labels:
      - "dependencies"
      - "docker"
      - "web"
      - "automated"

  # Docker dependencies for Admin
  - package-ecosystem: "docker"
    directory: "/apps/admin"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "12:00"
    open-pull-requests-limit: 3
    reviewers:
      - "taskmanagement/devops-team"
      - "taskmanagement/frontend-team"
    labels:
      - "dependencies"
      - "docker"
      - "admin"
      - "automated"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "taskmanagement/devops-team"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"