/**
 * Audit Action Enumeration
 */
export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PERMISSION_CHANGE = 'PERMISSION_CHANGE',
  ARCHIVE = 'ARCHIVE',
  RESTORE = 'RESTORE',
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  SHARE = 'SHARE',
  ASSIGN = 'ASSIGN',
  UNASSIGN = 'UNASSIGN',
  COMMENT = 'COMMENT',
  UPLOAD = 'UPLOAD',
  DOWNLOAD = 'DOWNLOAD',
  MOVE = 'MOVE',
  COPY = 'COPY',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SUSPEND = 'SUSPEND',
  ACTIVATE = 'ACTIVATE',
  ACCESS = 'ACCESS'
}

/**
 * Activity Type Enumeration
 */
export enum ActivityType {
  USER_ACTION = 'USER_ACTION',
  SYSTEM_ACTION = 'SYSTEM_ACTION',
  INTEGRATION_ACTION = 'INTEGRATION_ACTION',
  SCHEDULED_ACTION = 'SCHEDULED_ACTION',
  API_ACTION = 'API_ACTION',
  WEBHOOK_ACTION = 'WEBHOOK_ACTION',
  SECURITY_EVENT = 'SECURITY_EVENT',
  ERROR_EVENT = 'ERROR_EVENT',
  PERFORMANCE_EVENT = 'PERFORMANCE_EVENT'
}
