packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
  - 'docs/*'

# Exclude test and build directories
exclude:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/.next/**'
  - '**/coverage/**'
  - '**/test-results/**'