global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${ALERT_EMAIL_FROM}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true
  
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
      
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h
      
    - match:
        service: database
      receiver: 'database-team'
      group_wait: 15s
      repeat_interval: 1h
      
    - match:
        service: auth
      receiver: 'security-team'
      group_wait: 5s
      repeat_interval: 15m
      
    - match:
        service: business
      receiver: 'product-team'
      group_wait: 1m
      repeat_interval: 4h

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
    
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: '${DEFAULT_EMAIL_TO}'
        subject: '[TaskManagement] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
        severity: 'critical'
    
    slack_configs:
      - api_url: '${SLACK_CRITICAL_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'Critical Alert'
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'danger'
    
    email_configs:
      - to: '${CRITICAL_EMAIL_TO}'
        subject: '[CRITICAL] TaskManagement Alert: {{ .GroupLabels.alertname }}'

  - name: 'warning-alerts'
    slack_configs:
      - api_url: '${SLACK_WARNING_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: 'Warning Alert'
        color: 'warning'
    
    email_configs:
      - to: '${WARNING_EMAIL_TO}'
        subject: '[WARNING] TaskManagement Alert: {{ .GroupLabels.alertname }}'

  - name: 'database-team'
    email_configs:
      - to: '${DATABASE_TEAM_EMAIL}'
        subject: '[DATABASE] TaskManagement Alert: {{ .GroupLabels.alertname }}'

  - name: 'security-team'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_SECURITY_ROUTING_KEY}'
        severity: 'critical'
    
    email_configs:
      - to: '${SECURITY_TEAM_EMAIL}'
        subject: '[SECURITY] TaskManagement Alert: {{ .GroupLabels.alertname }}'

  - name: 'product-team'
    email_configs:
      - to: '${PRODUCT_TEAM_EMAIL}'
        subject: '[BUSINESS METRICS] TaskManagement Alert: {{ .GroupLabels.alertname }}'