groups:
  - name: taskmanagement.rules
    rules:
      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

      # High Disk Usage Alert
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 10m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "High disk usage detected on {{ $labels.instance }}"
          description: "Disk usage is above 90% for more than 10 minutes on {{ $labels.instance }} at {{ $labels.mountpoint }}"

      # API Response Time Alert
      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, method, route)) > 1
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High API response time detected"
          description: "95th percentile response time is above 1 second for {{ $labels.method }} {{ $labels.route }}"

      # High Error Rate Alert
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for more than 5 minutes"

      # Database Connection Alert
      - alert: DatabaseConnectionFailure
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database connection failure"
          description: "Cannot connect to PostgreSQL database"

      # Redis Connection Alert
      - alert: RedisConnectionFailure
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis connection failure"
          description: "Cannot connect to Redis cache"

      # Service Down Alert
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute"

      # Low User Engagement Alert
      - alert: LowUserEngagement
        expr: avg(user_engagement_score) < 0.3
        for: 30m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Low user engagement detected"
          description: "Average user engagement score is below 0.3 for more than 30 minutes"

      # Task Creation Rate Drop Alert
      - alert: TaskCreationRateDrop
        expr: rate(tasks_created_total[1h]) < 0.1
        for: 1h
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Task creation rate has dropped significantly"
          description: "Task creation rate is below 0.1 tasks per second for more than 1 hour"