blank_issues_enabled: false
contact_links:
  - name: 🔒 Critical Security Vulnerability
    url: mailto:security@taskmanagement.app
    about: Report critical security vulnerabilities privately via email
  - name: 💬 General Discussion
    url: https://github.com/taskmanagement/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://docs.taskmanagement.app
    about: Check our documentation for answers to common questions
  - name: 🆘 Support
    url: https://support.taskmanagement.app
    about: Get help with using the application