/**
 * Error codes and messages
 */

/**
 * Domain error codes
 */
export const DOMAIN_ERROR_CODES = {
  VALIDATION_FAILED: 'DOMAIN_VALIDATION_FAILED',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  AGGREGATE_NOT_FOUND: 'AGGREGATE_NOT_FOUND',
  INVALID_OPERATION: 'INVALID_OPERATION',
} as const;

/**
 * Application error codes
 */
export const APPLICATION_ERROR_CODES = {
  USE_CASE_FAILED: 'USE_CASE_FAILED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  COMMAND_VALIDATION_FAILED: 'COMMAND_VALIDATION_FAILED',
  QUERY_FAILED: 'QUERY_FAILED',
} as const;

/**
 * Infrastructure error codes
 */
export const INFRASTRUCTURE_ERROR_CODES = {
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  EXTERNAL_SERVICE_FAILED: 'EXTERNAL_SERVICE_FAILED',
  CACHE_OPERATION_FAILED: 'CACHE_OPERATION_FAILED',
  FILE_OPERATION_FAILED: 'FILE_OPERATION_FAILED',
} as const;

/**
 * Authentication error codes
 */
export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MFA_REQUIRED: 'MFA_REQUIRED',
} as const;
