/**
 * Error codes and messages
 * Enhanced with comprehensive error categorization from older version
 */

/**
 * Domain error codes
 */
export const DOMAIN_ERROR_CODES = {
  VALIDATION_FAILED: 'DOMAIN_VALIDATION_FAILED',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  AGGREGATE_NOT_FOUND: 'AGGREGATE_NOT_FOUND',
  INVALID_OPERATION: 'INVALID_OPERATION',
} as const;

/**
 * Application error codes
 */
export const APPLICATION_ERROR_CODES = {
  USE_CASE_FAILED: 'USE_CASE_FAILED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  COMMAND_VALIDATION_FAILED: 'COMMAND_VALIDATION_FAILED',
  QUERY_FAILED: 'QUERY_FAILED',
} as const;

/**
 * Infrastructure error codes
 */
export const INFRASTRUCTURE_ERROR_CODES = {
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  EXTERNAL_SERVICE_FAILED: 'EXTERNAL_SERVICE_FAILED',
  CACHE_OPERATION_FAILED: 'CACHE_OPERATION_FAILED',
  FILE_OPERATION_FAILED: 'FILE_OPERATION_FAILED',
} as const;

/**
 * Authentication error codes
 */
export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MFA_REQUIRED: 'MFA_REQUIRED',
} as const;

/**
 * Validation error codes
 */
export const VALIDATION_ERROR_CODES = {
  INVALID_INPUT: 'INVALID_INPUT',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_FORMAT: 'INVALID_FORMAT',
  VALUE_OUT_OF_RANGE: 'VALUE_OUT_OF_RANGE',
  INVALID_TYPE: 'INVALID_TYPE',
  SCHEMA_VALIDATION_FAILED: 'SCHEMA_VALIDATION_FAILED',
  DUPLICATE_VALUE: 'DUPLICATE_VALUE',
  INVALID_ENUM_VALUE: 'INVALID_ENUM_VALUE',
} as const;

/**
 * HTTP error codes
 */
export const HTTP_ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

/**
 * Business logic error codes
 */
export const BUSINESS_ERROR_CODES = {
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  TASK_ALREADY_COMPLETED: 'TASK_ALREADY_COMPLETED',
  TASK_NOT_ASSIGNED: 'TASK_NOT_ASSIGNED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  WORKSPACE_INACTIVE: 'WORKSPACE_INACTIVE',
  USER_NOT_MEMBER: 'USER_NOT_MEMBER',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  DEADLINE_PASSED: 'DEADLINE_PASSED',
  DEPENDENCY_NOT_MET: 'DEPENDENCY_NOT_MET',
} as const;

/**
 * System error codes
 */
export const SYSTEM_ERROR_CODES = {
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  STARTUP_FAILED: 'STARTUP_FAILED',
  SHUTDOWN_FAILED: 'SHUTDOWN_FAILED',
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  BACKUP_FAILED: 'BACKUP_FAILED',
  RESTORE_FAILED: 'RESTORE_FAILED',
} as const;

/**
 * Integration error codes
 */
export const INTEGRATION_ERROR_CODES = {
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
  EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',
  SMS_DELIVERY_FAILED: 'SMS_DELIVERY_FAILED',
  PUSH_NOTIFICATION_FAILED: 'PUSH_NOTIFICATION_FAILED',
  CALENDAR_SYNC_FAILED: 'CALENDAR_SYNC_FAILED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  IMPORT_FAILED: 'IMPORT_FAILED',
} as const;

/**
 * Security error codes
 */
export const SECURITY_ERROR_CODES = {
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  BRUTE_FORCE_DETECTED: 'BRUTE_FORCE_DETECTED',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  XSS_ATTEMPT_DETECTED: 'XSS_ATTEMPT_DETECTED',
  SQL_INJECTION_DETECTED: 'SQL_INJECTION_DETECTED',
} as const;

/**
 * Performance error codes
 */
export const PERFORMANCE_ERROR_CODES = {
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  MEMORY_LIMIT_EXCEEDED: 'MEMORY_LIMIT_EXCEEDED',
  CPU_LIMIT_EXCEEDED: 'CPU_LIMIT_EXCEEDED',
  DISK_SPACE_LOW: 'DISK_SPACE_LOW',
  CONNECTION_POOL_EXHAUSTED: 'CONNECTION_POOL_EXHAUSTED',
  QUEUE_FULL: 'QUEUE_FULL',
  CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',
} as const;

/**
 * All error codes combined for easy access
 */
export const ALL_ERROR_CODES = {
  ...DOMAIN_ERROR_CODES,
  ...APPLICATION_ERROR_CODES,
  ...INFRASTRUCTURE_ERROR_CODES,
  ...AUTH_ERROR_CODES,
  ...VALIDATION_ERROR_CODES,
  ...HTTP_ERROR_CODES,
  ...BUSINESS_ERROR_CODES,
  ...SYSTEM_ERROR_CODES,
  ...INTEGRATION_ERROR_CODES,
  ...SECURITY_ERROR_CODES,
  ...PERFORMANCE_ERROR_CODES,
} as const;

/**
 * Error severity levels
 */
export const ERROR_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;

/**
 * Error categories for grouping and filtering
 */
export const ERROR_CATEGORIES = {
  DOMAIN: 'domain',
  APPLICATION: 'application',
  INFRASTRUCTURE: 'infrastructure',
  AUTHENTICATION: 'authentication',
  VALIDATION: 'validation',
  HTTP: 'http',
  BUSINESS: 'business',
  SYSTEM: 'system',
  INTEGRATION: 'integration',
  SECURITY: 'security',
  PERFORMANCE: 'performance',
} as const;
