version: '3.8'

services:
  # Override for development
  api:
    build:
      target: development
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    volumes:
      - ../../apps/api:/app/apps/api
      - ../../packages:/app/packages
      - /app/node_modules
      - /app/apps/api/node_modules
    command: ["pnpm", "--filter", "api", "dev"]

  web:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ../../apps/web:/app/apps/web
      - ../../packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    command: ["pnpm", "--filter", "web", "dev"]

  admin:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ../../apps/admin:/app/apps/admin
      - ../../packages:/app/packages
      - /app/node_modules
      - /app/apps/admin/node_modules
      - /app/apps/admin/.next
    command: ["pnpm", "--filter", "admin", "dev"]

  # Development tools
  mailhog:
    image: mailhog/mailhog:latest
    container_name: taskmanagement-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - taskmanagement-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: taskmanagement-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskmanagement.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - taskmanagement-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: taskmanagement-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD:-taskmanagement}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - taskmanagement-network

volumes:
  pgadmin_data:
    driver: local