apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: taskmanagement-api-pdb
  namespace: taskmanagement
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: taskmanagement-web-pdb
  namespace: taskmanagement
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web