apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskmanagement-api
  namespace: taskmanagement
  labels:
    app.kubernetes.io/component: api
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskmanagement-web
  namespace: taskmanagement
  labels:
    app.kubernetes.io/component: web
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskmanagement-admin
  namespace: taskmanagement
  labels:
    app.kubernetes.io/component: admin
automountServiceAccountToken: false