web:
  port: 3001
  address: "0.0.0.0"

storage:
  type: memory

endpoints:
  - name: "API Health Check"
    url: "http://api:3000/health"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
    alerts:
      - type: email
        enabled: true
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
        description: "API health check failed"

  - name: "Web Application"
    url: "http://web:3001/health"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
    alerts:
      - type: email
        enabled: true
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
        description: "Web application health check failed"

  - name: "Admin Dashboard"
    url: "http://admin:3002/health"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
    alerts:
      - type: email
        enabled: true
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
        description: "Admin dashboard health check failed"

  - name: "Database Connection"
    url: "http://api:3000/health/database"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].database.status == UP"
    alerts:
      - type: email
        enabled: true
        send-on-resolved: true
        failure-threshold: 2
        success-threshold: 1
        description: "Database connection check failed"

  - name: "Redis Cache"
    url: "http://api:3000/health/cache"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].cache.status == UP"
    alerts:
      - type: email
        enabled: true
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
        description: "Redis cache health check failed"

alerting:
  email:
    from: "uptime@taskmanagement.com"
    username: "uptime@taskmanagement.com"
    password: "your-email-password"
    host: "smtp.gmail.com"
    port: 587
    to: "devops@taskmanagement.com"
    default-subject: "[TaskManagement] Uptime Alert"