apiVersion: v2
name: taskmanagement
description: A Helm chart for TaskManagement application
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/your-org/taskmanagement
sources:
  - https://github.com/your-org/taskmanagement
maintainers:
  - name: TaskManagement Team
    email: team@taskmanagement.com
keywords:
  - taskmanagement
  - productivity
  - collaboration
  - nodejs
  - react
annotations:
  category: Productivity