global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'taskmanagement'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # API Server Metrics
  - job_name: 'taskmanagement-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Web Application Metrics
  - job_name: 'taskmanagement-web'
    static_configs:
      - targets: ['web:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Admin Dashboard Metrics
  - job_name: 'taskmanagement-admin'
    static_configs:
      - targets: ['admin:3002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # Jaeger Metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: '/metrics'

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['metrics-collector:8080']
    scrape_interval: 30s