apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskmanagement

resources:
- namespace.yaml
- configmap.yaml
- postgres.yaml
- redis.yaml
- server.yaml
- client.yaml
- ingress.yaml

images:
- name: taskmanagement/server
  newTag: latest
- name: taskmanagement/client
  newTag: latest

commonLabels:
  app.kubernetes.io/name: taskmanagement
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: fullstack-app

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: server-deployment
    namespace: taskmanagement
  spec:
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "3001"
          prometheus.io/path: "/metrics"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: client-deployment
    namespace: taskmanagement
  spec:
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "3000"
          prometheus.io/path: "/api/metrics"