# Codecov Configuration for Task Management App
# Code coverage reporting and analysis

codecov:
  # Require CI to pass before merging
  require_ci_to_pass: true
  
  # Notify settings
  notify:
    # Require coverage to pass before merging
    require_ci_to_pass: true
    
    # Wait for CI to complete
    wait_for_ci: true

# Coverage configuration
coverage:
  # Precision of coverage percentage
  precision: 2
  
  # Round coverage percentage
  round: down
  
  # Coverage range (red to green)
  range: "70...100"
  
  # Status checks
  status:
    # Project coverage
    project:
      default:
        # Target coverage percentage
        target: 80%
        # Threshold for coverage drop
        threshold: 1%
        # Base branch for comparison
        base: auto
        # Require coverage to increase
        if_ci_failed: error
        # Require coverage on new code
        if_not_found: success
        # Only check coverage on changed files
        only_pulls: false
    
    # Patch coverage (new code)
    patch:
      default:
        # Target coverage for new code
        target: 85%
        # Threshold for new code coverage
        threshold: 5%
        # Base branch for comparison
        base: auto
        # Require coverage on new code
        if_ci_failed: error
        # Require coverage on new code
        if_not_found: failure
        # Only check coverage on pull requests
        only_pulls: true

  # Changes configuration
  changes:
    default:
      # Require coverage on changed files
      target: auto
      # Threshold for changed files
      threshold: 1%
      # Base branch for comparison
      base: auto
      # Require coverage on changed files
      if_ci_failed: error
      # Require coverage on changed files
      if_not_found: success

# Comment configuration
comment:
  # Layout of the comment
  layout: "reach,diff,flags,tree,reach"
  
  # Behavior settings
  behavior: default
  
  # Require changes to post comment
  require_changes: false
  
  # Require base coverage to post comment
  require_base: no
  
  # Require head coverage to post comment
  require_head: yes
  
  # Show coverage for all files
  show_all_paths: false
  
  # Show critical files
  show_critical_paths: true

# Ignore paths
ignore:
  - "node_modules"
  - "dist"
  - "build"
  - ".next"
  - "coverage"
  - "test-results"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.stories.ts"
  - "**/*.stories.tsx"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/test/**"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/e2e/**"
  - "**/tools/**"
  - "**/scripts/**"
  - "**/docs/**"
  - "**/*.d.ts"
  - "**/migrations/**"
  - "**/seeds/**"
  - "**/generated/**"

# Flags for different parts of the codebase
flags:
  # Core packages
  core:
    paths:
      - packages/core/
    carryforward: true
  
  # Domain package
  domain:
    paths:
      - packages/domain/
    carryforward: true
  
  # Database package
  database:
    paths:
      - packages/database/
    carryforward: true
  
  # Authentication package
  auth:
    paths:
      - packages/auth/
    carryforward: true
  
  # Validation package
  validation:
    paths:
      - packages/validation/
    carryforward: true
  
  # API application
  api:
    paths:
      - apps/api/
    carryforward: true
  
  # Web application
  web:
    paths:
      - apps/web/
    carryforward: true
  
  # Admin application
  admin:
    paths:
      - apps/admin/
    carryforward: true
  
  # Mobile application
  mobile:
    paths:
      - apps/mobile/
    carryforward: true
  
  # UI package
  ui:
    paths:
      - packages/ui/
    carryforward: true
  
  # Utilities package
  utils:
    paths:
      - packages/utils/
    carryforward: true
  
  # Unit tests
  unit:
    paths:
      - "**/*.test.ts"
      - "**/*.test.tsx"
      - "**/*.spec.ts"
      - "**/*.spec.tsx"
    carryforward: false
  
  # Integration tests
  integration:
    paths:
      - "**/integration/**"
      - "**/*.integration.test.ts"
    carryforward: false
  
  # E2E tests
  e2e:
    paths:
      - "**/e2e/**"
      - "**/*.e2e.test.ts"
    carryforward: false

# GitHub checks
github_checks:
  annotations: true

# Slack notifications (if configured)
slack_app:
  # Enable Slack notifications
  enabled: false
  
  # Slack webhook URL (set in Codecov settings)
  # url: "https://hooks.slack.com/services/..."
  
  # Notification settings
  notify:
    # Notify on coverage changes
    coverage_change: true
    
    # Notify on build failures
    build_failure: true
    
    # Notify on successful builds
    build_success: false

# Profiling
profiling:
  # Enable critical files detection
  critical_files_paths:
    - packages/core/
    - packages/domain/
    - packages/auth/
    - packages/validation/

# Carryforward flags
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: "project"
        target: "80%"
      - type: "patch"
        target: "85%"

# Parsers configuration
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Component management
component_management:
  default_rules:
    statuses:
      - type: "project"
        target: "80%"
      - type: "patch"
        target: "85%"
  
  individual_components:
    - component_id: "core"
      name: "Core Package"
      paths:
        - "packages/core/**"
      statuses:
        - type: "project"
          target: "90%"
        - type: "patch"
          target: "95%"
    
    - component_id: "domain"
      name: "Domain Package"
      paths:
        - "packages/domain/**"
      statuses:
        - type: "project"
          target: "85%"
        - type: "patch"
          target: "90%"
    
    - component_id: "api"
      name: "API Application"
      paths:
        - "apps/api/**"
      statuses:
        - type: "project"
          target: "80%"
        - type: "patch"
          target: "85%"
    
    - component_id: "web"
      name: "Web Application"
      paths:
        - "apps/web/**"
      statuses:
        - type: "project"
          target: "75%"
        - type: "patch"
          target: "80%"
    
    - component_id: "ui"
      name: "UI Package"
      paths:
        - "packages/ui/**"
      statuses:
        - type: "project"
          target: "85%"
        - type: "patch"
          target: "90%"