name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Update dependencies
      run: |
        npm update
        npm audit fix --audit-level moderate

    - name: Run tests
      run: |
        npm ci
        npm run test:unit

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated dependency updates'
        body: |
          This PR contains automated dependency updates.
          
          Please review the changes and ensure all tests pass before merging.
        branch: dependency-updates
        delete-branch: true

  security-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level high

    - name: Update Docker base images
      run: |
        # Update base images in Dockerfiles
        sed -i 's/node:18-alpine/node:18-alpine/g' apps/server/Dockerfile
        sed -i 's/node:18-alpine/node:18-alpine/g' apps/client/Dockerfile
        sed -i 's/postgres:15-alpine/postgres:15-alpine/g' docker-compose.yml
        sed -i 's/redis:7-alpine/redis:7-alpine/g' docker-compose.yml

    - name: Create security update PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'security: update base images and dependencies'
        title: 'Security updates for base images and dependencies'
        body: |
          This PR contains security updates for:
          - Docker base images
          - Node.js dependencies with known vulnerabilities
          
          Please review and test thoroughly before merging.
        branch: security-updates
        delete-branch: true